
x-logging: &default_logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_gateway

    ports:
      - "${NGINX_PORT:-80}:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      geoserver:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - irrigation_network

    logging: *default_logging


  frontend:
    build:
      context: ./frontend
      target: prod

    container_name: frontend

    restart: unless-stopped

    networks:
      - irrigation_network

    logging: *default_logging


  backend:
    build:
      context: ./backend

    container_name: backend

    volumes:
      - ${BACKEND_DATA_DIR:-./backend/data}:/app/data
      - ./backend/.env:/app/.env:ro
      - ./backend/service_account_key.json:/app/service_account_key.json:ro

    environment:
      PYTHONUNBUFFERED: "1"

      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB: ${MONGODB_DB:-irrigation_db}

      GEOSERVER_URL: http://geoserver:8080/geoserver
      GEOSERVER_USER: ${GEOSERVER_ADMIN_USER:-admin}
      GEOSERVER_PASS: ${GEOSERVER_ADMIN_PASSWORD:-geoserver}
      GEOSERVER_WORKSPACE: ${GEOSERVER_WORKSPACE:-irrigation}

      GOOGLE_APPLICATION_CREDENTIALS: /app/service_account_key.json

      # OLLAMA CONFIG
      OLLAMA_HOST: http://ollama:11434

    depends_on:
      mongodb:
        condition: service_started

      geoserver:
        condition: service_healthy

      ollama:
        condition: service_started

    restart: unless-stopped

    shm_size: "2gb"

    networks:
      - irrigation_network

    logging: *default_logging


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - irrigation_network
    logging: *default_logging
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 15 &&
        ollama pull llama3.2:3b &&
        ollama pull qwen2.5:3b && configs:
        ollama pull nomic-embed-text &&
        wait
      "
  
  


  mongodb:
    image: mongo:7

    container_name: mongodb

    ports:
      - "${MONGO_PORT:-27017}:27017"

    restart: unless-stopped

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - irrigation_network

    logging: *default_logging


  geoserver:
    build:
      context: ./geoserver
      
    image: iirs-geoserver

    container_name: geoserver

    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
      OLLAMA_HOST: http://ollama:11434

    volumes:
      - ${BACKEND_DATA_DIR:-./backend/data}:/app/data:ro
      - ./geoserver/data_dir:/opt/geoserver/data_dir
      # - ${BACKEND_DATA_DIR:-./backend/data}:/home/aman/web_world/Web_Project/irr/IIRS/backend/data:ro

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/geoserver/web/ >/dev/null || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 90s

    restart: unless-stopped

    networks:
      - irrigation_network

    logging: *default_logging


volumes:
  mongo_data:
  ollama_data:


networks:
  irrigation_network:
    driver: bridge

