apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaldrishti-ingress
  namespace: jaldrishti
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: jaldrishti.iirs.gov.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /geoserver
        pathType: Prefix
        backend:
          service:
            name: geoserver
            port:
              number: 8080